default: &default
  pageTimeOut: 30
  objectTimeOut: 30

google:
  <<: *default
  login_url: https://www.google.com/

facebook:
  login_url: https://www.facebook.com/
  page_timeout: 30
  object_timeout: 30